apiVersion: v1
kind: Namespace
metadata:
  name: project1

---

# Auth Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: project1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: rev3rb698/auth-service:latest
          ports:
          - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"


---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: project1
spec:
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP

---

# Data Entry Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-entry-service
  namespace: project1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: data-entry-service
  template:
    metadata:
      labels:
        app: data-entry-service
    spec:
      containers:
      - name: data-entry-service
        image: rev3rb698/data-entry-service:latest
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: data-entry-service
  namespace: project1
spec:
  selector:
    app: data-entry-service
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  type: ClusterIP

---

# Analytics Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: project1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: rev3rb698/analytics-service:latest
          ports:
          - containerPort: 5002
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: project1
spec:
  selector:
    app: analytics-service
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
  type: ClusterIP

---

# Show Results Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: show-results-service
  namespace: project1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: show-results-service
  template:
    metadata:
      labels:
        app: show-results-service
    spec:
      containers:
      - name: show-results-service
        image: rev3rb698/show-results-service:latest
        ports:
        - containerPort: 5003
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: show-results-service
  namespace: project1
spec:
  selector:
    app: show-results-service
  ports:
  - protocol: TCP
    port: 5003
    targetPort: 5003
  type: ClusterIP

---

# HTML Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-service
  namespace: project1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-service
  template:
    metadata:
      labels:
        app: html-service
    spec:
      containers:
      - name: html-service
        image: rev3rb698/html-service:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: html-service
  namespace: project1
spec:
  selector:
    app: html-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

---

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: project1
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: project1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: student_db
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

      volumes:
      - name: mysql-persistent-storage
        emptyDir: {}
---
# Horizontal Pod Autoscaler for Data Entry Service
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: data-entry-hpa
  namespace: project1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: data-entry-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50

